# -*- coding: utf-8 -*-
"""bill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCyV2VgfHS0p0Dghw6V2fLU2OZRH2Qkl
"""

print("WELCOME TO DEV STORE")
item1=float(input("Enter the price "))
item2=float(input("Enter the price "))
item3=float(input("Enter the price "))
amount=item1+item2+item3
print("Before discount",amount)
if(amount>50):
  print("After discount bill is : ",amount-(amount*0.1))
else:
  print("After discount bill is : ",amount)